CREATE PROCEDURE nbrMembre()
RESULT (nbr INTEGER)
BEGIN
    SELECT COUNT(username) FROM tbUsers;
END

CREATE SERVICE "membre" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" METHODS 'GET' AS CALL nbrMembre();